# Generated by Django 5.2.6 on 2025-09-16 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fashion olahraga', 'Fashion Olahraga'), ('peralatan Olahraga', 'Peralatan Olahraga'), ('suplemen Olahraga', 'Suplemen Olahraga'), ('kesehatan dan kebugaran', 'Kesehatan dan Kebugaran'), ('bola', 'Bola')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
