# Generated by Django 5.2.6 on 2025-09-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_views_alter_item_category_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
        migrations.AddField(
            model_name='item',
            name='items_views',
            field=models.IntegerField(default=0),
        ),
    ]
