# Generated by Django 5.2.6 on 2025-09-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_views_item_items_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items_views',
        ),
    ]
