# Generated by Django 5.2.6 on 2025-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fashion olahraga', 'Fashion Olahraga'), ('peralatan olahraga', 'Peralatan Olahraga'), ('suplemen olahraga', 'Suplemen Olahraga'), ('kesehatan dan kebugaran', 'Kesehatan dan Kebugaran'), ('bola', 'Bola')], max_length=50),
        ),
    ]
